name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create necessary files
      shell: cmd
      run: |
        rem 创建配置文件
        echo { > config.json.example
        echo   "ncbi_key": "your_ncbi_key_here", >> config.json.example
        echo   "dashscope_key": "your_dashscope_key_here", >> config.json.example
        echo   "search_term": "example search term", >> config.json.example
        echo   "retmax": "20" >> config.json.example
        echo } >> config.json.example
        
        rem 创建 README
        if not exist README.md (
          echo # Literature Analysis Tool > README.md
          echo A tool for analyzing scientific literature >> README.md
        )
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pandas numpy matplotlib reportlab dashscope requests
    
    - name: Check Directory Structure
      shell: cmd
      run: |
        dir
        if exist literature_analysis (
          dir literature_analysis
        ) else (
          echo literature_analysis directory not found
        )
    
    - name: Build with PyInstaller
      shell: cmd
      run: |
        dir
        pyinstaller --name=literature_analysis ^
                   --onefile ^
                   --noconsole ^
                   --add-data "README.md;." ^
                   --add-data "config.json.example;." ^
                   --hidden-import pandas ^
                   --hidden-import numpy ^
                   --hidden-import matplotlib ^
                   --hidden-import reportlab ^
                   --hidden-import dashscope ^
                   literature_analysis/main.py
        dir dist
    
    - name: Create Release Package
      shell: cmd
      run: |
        mkdir release_package
        dir dist
        copy "dist\literature_analysis.exe" "release_package\"
        copy "README.md" "release_package\"
        copy "config.json.example" "release_package\"
        echo Package contents:
        dir release_package
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.3
      with:
        name: literature_analysis_windows
        path: release_package
        if-no-files-found: error
        retention-days: 30
