name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Create necessary files
      shell: cmd
      run: |
        rem 创建配置文件
        echo { > config.json.example
        echo   "ncbi_key": "your_ncbi_key_here", >> config.json.example
        echo   "dashscope_key": "your_dashscope_key_here", >> config.json.example
        echo   "search_term": "example search term", >> config.json.example
        echo   "retmax": "20" >> config.json.example
        echo } >> config.json.example
        
        rem 创建 README
        if not exist README.md (
          echo # Literature Analysis Tool > README.md
          echo A tool for analyzing scientific literature >> README.md
        )
        
        rem 显示创建的文件
        dir
        type config.json.example
    
    - name: List files in repository
      run: |
        dir
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pandas numpy matplotlib reportlab dashscope
    
    - name: Build with PyInstaller
      run: |
              pyinstaller --name=literature_analysis `
                   --onefile `
                   --noconsole `
                   --add-data "README.md;." `
                   --add-data "config.json.example;." `
                   --hidden-import pandas `
                   --hidden-import numpy `
                   --hidden-import matplotlib `
                   --hidden-import reportlab `
                   --hidden-import dashscope `
                   literature_analysis/main.py  
    
    - name: List generated files
      run: |
        dir dist
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: literature_analysis.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
